When To Retire.
JacobAMason/Software-Testing-and-QA pull request #18
Opened 2017-02-24 13:04 UTC by EliCDavis

Created a function that would determine when a person could retire.  Some boundaries could be vague at what to do at them and might require further clarification.  As of now it does a lot of parameter checking.

Closes #3

2017-02-24 13:05 UTC, EliCDavis commented
Oh one line doesn't get hit huh.  One second

2017-02-24 14:12 UTC, JacobAMason requested changes
I can think of another test: if the goal is 0, the salary and savings could be 0 and the goal would be met at the current age. It might be more than it's worth for this one exception, though.

2017-02-24 14:12 UTC, JacobAMason commented on Assignment1/retirement.py
> +        raise ValueError("Can not have a positive salary")
I think this should say "Can not have a negative salary" or "Salary must be greater than 0"

2017-02-24 14:12 UTC, JacobAMason commented on Assignment1/retirement.py
> +def year_can_retire(age, salary, saving, goal):
Might want to rename "saving" to "savingPercent" or something that makes it clear that this value is a percentage. Even though I knew it was a percentage, my brain kept wanting to swap in "savings" instead.

2017-02-24 23:47 UTC, EliCDavis commented
@JacobAMason I've taken into account your suggestions and then created test classes to break up everything.

2017-02-25 04:18 UTC, JacobAMason approved these changes

2017-02-25 04:18 UTC, merged